#! ---------------------------------------------------------------
#! Aurora Theme for Hexo
#! ---------------------------------------------------------------
#! Designed & Coded By TriDiamond
#! ---------------------------------------------------------------

#! ---------------------------------------------------------------
#! Site Configs
#ï¼ @docs https://aurora.tridiamond.tech/guide/configuration.html
#! ---------------------------------------------------------------
site:
  subtitle: hailong's Blog
  author: é™ˆæµ·é¾™
  nick: Sarmatã€Œè¯·ä½¿ç”¨httpè®¿é—®ã€
  description: 'éœ€è¦å°±å­¦å‘—ï¼Œå¤šå¤§ç‚¹äº‹ğŸ˜‚'
  link: '/'
  language: en
  multi_language: true
  logo: https://img-blog.csdnimg.cn/20210313122054101.png
  avatar: http://t-blog-images.aijs.top/img/avatar.jpeg
  beian:
    number: ''
    link: ''
  police_beian:
    number: ''
    link: ''

#! ---------------------------------------------------------------
#! Menu Configs
#ï¼ @docs https://aurora.tridiamond.tech/guide/menu.html
#! ---------------------------------------------------------------
menu:
  About: true
  Tags: true
  Archives: true
  Aurora:
    name: 'Aurora'
    path: 'https://github.com/Aurora/hexo-theme-Aurora'

#! ---------------------------------------------------------------
#! Theme Config
#! @docs https://aurora.tridiamond.tech/guide/theme.html
#! ---------------------------------------------------------------
theme:
  dark_mode: true
  profile_shape: diamond # support `circle`, `diamond`, `rounded`
  feature: true
  gradient:
    color_1: '#24c6dc'
    color_2: '#5433ff'
    color_3: '#ff0099'

#! ---------------------------------------------------------------
#! Social Configs
#! @docs https://aurora.tridiamond.tech/guide/social.html
#! ---------------------------------------------------------------
socials:
  github: 'https://github.com/841660202'
  # twitter: ''
  # stackoverflow: ''
  # weibo: 'https://weibo.com/u/7318914058'
  # zhihu: 'https://www.zhihu.com/people/tridiamond'
  csdn: 'https://blog.csdn.net/web_longboss'
  # juejin: 'https://juejin.cn/user/1873223546578589'
  customs:
  ##! Example:
  ##! --- Using SVG
  # bilibili:
  #   icon: http://localhost:4000/svg/bilibili.svg
  #   link: https://live.bilibili.com/22619211

  ##! --- Using IconFont
  # baidu:
  #   icon: iconfont icon-baidu
  #   link: https://live.bilibili.com/22619211

  ##! --- Using FontAwesome
  # book:
  #   icon: far fa-address-book
  #   link: https://live.bilibili.com/22619211

#! ---------------------------------------------------------------
#! Site Meta Configs
#! @docs https://aurora.tridiamond.tech/guide/theme.html
#! ---------------------------------------------------------------
site_meta:
  cdn: cn
  favicon:
  description: ''
  keywords: ''
  author: ''

#! ---------------------------------------------------------------
#! Plugins
#! @docs https://aurora.tridiamond.tech/guide/plugins.html
#! ---------------------------------------------------------------

# For local development only!
gitalk:
  enable: false
  autoExpand: true
  clientID: ''
  clientSecret: ''
  repo: 'dev-blog-comments'
  owner: 'TriDiamond'
  admin: ['TriDiamond']
  id: uid
  language: en
  distractionFreeMode: true
  recentComment: true
  proxy: ''

# Valine comment plugin (recommended!)
# see https://valine.js.org/quickstart.html
valine:
  enable: true
  app_id: Yk9jGEffaQNJV0JhYDnpvDJi-gzGzoHsz
  app_key: fzEW1QacjPN8Oddn8VehBS8S
  avatar: 'http://t-blog-images.aijs.top/img/avatar.jpeg'
  placeholder: Leave your thoughts behind~
  visitor: true
  lang: en
  avatarForce: false
  meta: ['nick', 'mail']
  requiredFields: []
  admin: 'æµ·é¾™'
  recentComment: true

# Enable Busuanzi statistic plugin
# see http://ibruce.info/2015/04/04/busuanzi/
busuanzi:
  enable: true

copy_protection:
  enable: false
  author:
    cn: ä½œè€…
    en: Author
  link:
    cn: æœ¬æ–‡æ¥è‡ªäº
    en: Article is from
  license:
    cn: åšå®¢å†…å®¹éµå¾ª ç½²å-éå•†ä¸šæ€§ä½¿ç”¨-ç›¸åŒæ–¹å¼å…±äº« 4.0 å›½é™… (CC BY-NC-SA 4.0) åè®®
    en: This content is shared under the CC BY-NC-SA 4.0 protocol (Non-Commercial)

#! ---------------------------------------------------------------
#! Enable Aurora Bot Dia
#! @docs https://aurora.tridiamond.tech/guide/site-meta.html#custom-meta
#! ---------------------------------------------------------------
aurora_bot:
  enable: false
  locale: en
  bot_type: dia
  tips:

#! ---------------------------------------------------------------
#! Injections
#! @docs https://aurora.tridiamond.tech/guide/site-meta.html#custom-meta
#! ---------------------------------------------------------------
injects:
  scripts:
  css:
